# Generated by Django 3.0.6 on 2020-08-18 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=200)),
                ('email', models.IntegerField()),
                ('telefone', models.CharField(max_length=200)),
                ('telefone_comercial', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Pessoa')),
                ('cpf', models.CharField(max_length=100)),
            ],
            bases=('blog.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Pessoa')),
                ('cnpj', models.CharField(max_length=25)),
            ],
            bases=('blog.pessoa',),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('codigo_barras', models.CharField(max_length=150)),
                ('valor_venda', models.CharField(max_length=10)),
                ('custo_medio', models.CharField(max_length=10)),
                ('data_cadastro', models.DateField()),
                ('unidade_medida', models.CharField(max_length=100)),
                ('ncm', models.CharField(max_length=100)),
                ('cest', models.CharField(max_length=100)),
                ('peso_liquido', models.CharField(max_length=100)),
                ('peso_bruto', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CategoriaProduto')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_disponivel', models.CharField(max_length=10)),
                ('estoque_minimo', models.CharField(max_length=10)),
                ('estoque_maximo', models.CharField(max_length=10)),
                ('data_de_cadastro', models.CharField(max_length=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorPF',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.PessoaFisica')),
                ('data_inicio', models.DateField()),
            ],
            bases=('blog.pessoafisica',),
        ),
    ]
