# Generated by Django 3.0.6 on 2020-05-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telefone_comercial', models.CharField(max_length=50)),
                ('Telefone_celular', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Observacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEP', models.CharField(max_length=100)),
                ('Logradouro', models.CharField(max_length=300)),
                ('Numero', models.CharField(max_length=100)),
                ('Complemento', models.CharField(max_length=100)),
                ('Bairro', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=60)),
                ('UF', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoEstadual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Indicador_de_inscricao_estadual', models.IntegerField(choices=[(0, 'Contribuinte'), (1, 'Não contribuinte,'), (2, 'Contribuinte isento')])),
                ('Inscricao_estadual', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('Status_do_usuario', models.BooleanField(default=False)),
                ('Perfil_de_acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.InscricaoEstadual')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Codigo', models.CharField(max_length=100)),
                ('Codigo_de_barras_EAN', models.CharField(max_length=100)),
                ('Valor_de_venda', models.CharField(max_length=100)),
                ('Custo_medio', models.FloatField()),
                ('Data_de_cadastro_do_produto', models.DateField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CategoriaProduto')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=100)),
                ('Razao_social', models.CharField(max_length=100)),
                ('Nome_fantasia', models.CharField(max_length=100)),
                ('Data_de_fundacao', models.DateField()),
                ('Inscricao_municipal', models.CharField(max_length=100)),
                ('Inscricao_SUFRAMA', models.CharField(max_length=100)),
                ('Optante_pelo_SIMPLES_Naconal', models.BooleanField(default=False)),
                ('Inscricao_estadual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.InscricaoEstadual')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=100)),
                ('RG', models.CharField(max_length=100)),
                ('Data_de_aniversario', models.DateField()),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil_de_acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status_do_fornecedor', models.IntegerField(choices=[(0, 'Ativo'), (1, 'Inativo')])),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estoque_disponivel', models.FloatField()),
                ('Estoque_minimo', models.FloatField()),
                ('Estoque_maximo', models.FloatField()),
                ('Data_de_cadastro', models.DateField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Produto')),
            ],
        ),
    ]
