# Generated by Django 3.1.1 on 2020-09-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=200)),
                ('telefone_comercial', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espessura', models.CharField(max_length=100)),
                ('comprimento', models.CharField(max_length=100)),
                ('largura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('horario_inicio', models.IntegerField()),
                ('horario_termino', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=100)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cnpj', models.CharField(max_length=25)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=100, verbose_name='Código')),
                ('codigo_barras', models.CharField(blank=True, max_length=150, verbose_name='Código de barras')),
                ('valor_venda', models.CharField(blank=True, max_length=10, verbose_name='Valor de venda')),
                ('custo_medio', models.CharField(blank=True, max_length=10, verbose_name='Custo médio')),
                ('data_cadastro', models.DateField()),
                ('unidade_medida', models.CharField(blank=True, max_length=100, verbose_name='Unidade de medida')),
                ('ncm', models.CharField(blank=True, max_length=100, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=100, verbose_name='CEST')),
                ('peso_liquido', models.CharField(blank=True, max_length=100, verbose_name='Peso líquido')),
                ('peso_bruto', models.CharField(blank=True, max_length=100, verbose_name='Peso bruto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.categoriaproduto')),
                ('dimensoes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmopi.dimensoes')),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_turno', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vigencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Compensado',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gmopi.produto')),
                ('numero_camadas', models.CharField(max_length=100, verbose_name='Número de camadas')),
            ],
            bases=('gmopi.produto',),
        ),
        migrations.CreateModel(
            name='FornecedorPF',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gmopi.pessoafisica')),
                ('data_inicio', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('gmopi.pessoafisica',),
        ),
        migrations.CreateModel(
            name='FornecedorPJ',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gmopi.pessoajuridica')),
                ('data_inicio', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('gmopi.pessoajuridica',),
        ),
        migrations.CreateModel(
            name='Lamina',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gmopi.produto')),
                ('classe', models.CharField(max_length=100)),
            ],
            bases=('gmopi.produto',),
        ),
        migrations.CreateModel(
            name='Tora',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gmopi.produto')),
                ('classe', models.CharField(max_length=100)),
                ('diametro', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
            ],
            bases=('gmopi.produto',),
        ),
        migrations.CreateModel(
            name='Laminadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.contato')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.vigencia')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.endereco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_disponivel', models.CharField(max_length=10, verbose_name='Estoque disponível')),
                ('estoque_minimo', models.CharField(blank=True, max_length=10, verbose_name='Estoque mínimo')),
                ('estoque_maximo', models.CharField(blank=True, max_length=10, verbose_name='Estoque máximo')),
                ('data_de_cadastro', models.CharField(blank=True, max_length=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('em_manutencao', models.BooleanField(help_text='O equipamento está em manutenção?')),
                ('data_aquisicao', models.DateField()),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aquisição', models.DateField()),
                ('plano_adquirido', models.CharField(max_length=100)),
                ('dia_vencimento', models.DateField()),
                ('vigencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmopi.vigencia')),
            ],
        ),
    ]
